<?php
/**
 * Created by PhpStorm.
 * User: Wind
 * Date: 2017/10/20
 * Time: 16:09
 */

namespace app\common\controller;

use think\Config;
use think\Controller;

class Base extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}